[spark] CDH-57150. Exit spark-shell/spark-submit/pyspark with correct error message if no client configuration found
Spark Applications fail with NoClassDefFound exception when spark applications are launched from a host which does not have client configurations (Spark Gateway role).

This fix adds a error message and exits application if it fails to find SPARK_DIST_CLASSPATH configured in the environment variable.

Testing Done:
Reproduced the issue by adding a new host to an existing cluster and ensured that the fix adds the error message. Also ensured that this error message is not printed when client configurations are available.

(cherry picked from commit f6b616f4eac3611eff4419dae79b18f514a16a4c)

diff --git a/bin/spark-class b/bin/spark-class
--- a/bin/spark-class
+++ b/bin/spark-class
@@ -23,6 +23,11 @@ fi
 
 . "${SPARK_HOME}"/bin/load-spark-env.sh
 
+if [ -z "$SPARK_TESTING" ] && [ -z "$SPARK_DIST_CLASSPATH" ]; then
+  echo "Failed to find client configuration. If this host is managed by Cloudera Manager, please install Spark Gateway Role on this host to run Spark Jobs. Otherwise, please configure the Spark dependencies correctly." 1>&2
+  exit 1
+fi
+
 # Find the java binary
 if [ -n "${JAVA_HOME}" ]; then
   RUNNER="${JAVA_HOME}/bin/java"
